name: Deploy Dev
on:
  push:
    branches:
      - master
    repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.VUE_APP_MAPBOX_ACCESS_TOKEN }}
        VUE_APP_MAP_STYLE_LIGHT: ${{ secrets.VUE_APP_MAP_STYLE_LIGHT }}
        VUE_APP_MAP_STYLE_DARK: ${{ secrets.VUE_APP_MAP_STYLE_DARK }}
      run: npm install
    - name: Build
      env:
        NODE_ENV: production
      run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          TARGET_FOLDER: dist