name: Deploy Dev
on:
  push:
    branches:
      - master
    repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        VUE_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.VUE_APP_MAPBOX_ACCESS_TOKEN }}
        VUE_APP_MAP_STYLE_LIGHT: ${{ secrets.VUE_APP_MAP_STYLE_LIGHT }}
        VUE_APP_MAP_STYLE_DARK: ${{ secrets.VUE_APP_MAP_STYLE_DARK }}
      run: npm install
    - name: Build
      env:
        NODE_ENV: production
      run: npm run build
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist